# Builds dist\ then compiles PES3-Disc-Setup.exe (Inno Setup).
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$installerDir = Join-Path $root 'installer'
$iss = Join-Path $installerDir 'PES3-Disc.iss'
$outDir = Join-Path $installerDir 'output'
$stageDir = Join-Path $installerDir 'stage'

function Escape-InnoString {
    param([string]$Value)
    return $Value.Replace('"', '""')
}

function Write-InnoFilesInclude {
    param(
        [string]$StageDir,
        [string]$OutPath
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('; Auto-generated by Build-Installer.ps1')
    $lines.Add('[Files]')
    foreach ($file in Get-ChildItem -Path $StageDir -Recurse -File | Sort-Object FullName) {
        $rel = $file.FullName.Substring($StageDir.Length).TrimStart('\').Replace('/', '\')
        $dest = '{app}'
        $parent = Split-Path $rel -Parent
        if ($parent) { $dest = "{app}\$($parent.Replace('/', '\'))" }
        $source = Escape-InnoString ("stage\$rel")
        $destEsc = Escape-InnoString $dest
        $lines.Add("Source: ""$source""; DestDir: ""$destEsc""; Flags: ignoreversion")
    }
    if ($lines.Count -le 2) {
        throw 'No files found in installer\stage for Inno [Files] section.'
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($OutPath, $lines, $utf8NoBom)
}

function Get-InnoSetupCompiler {
    $candidates = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
    )
    foreach ($path in $candidates) {
        if (Test-Path -LiteralPath $path) { return $path }
    }
    $cmd = Get-Command iscc -ErrorAction SilentlyContinue
    if ($cmd -and (Test-Path -LiteralPath $cmd.Source) -and $cmd.Source -notmatch 'Chocolatey\\bin') {
        return $cmd.Source
    }
    return $null
}

function Invoke-Iscc {
    param(
        [string]$Compiler,
        [string]$WorkingDir,
        [string]$Arguments,
        [string]$ConsoleLog
    )
    if (Test-Path -LiteralPath $ConsoleLog) {
        Remove-Item -LiteralPath $ConsoleLog -Force
    }
    $proc = Start-Process -FilePath 'cmd.exe' -ArgumentList @(
        '/c',
        "`"$Compiler`" $Arguments > `"$ConsoleLog`" 2>&1"
    ) -WorkingDirectory $WorkingDir -Wait -PassThru -NoNewWindow
    $text = if (Test-Path -LiteralPath $ConsoleLog) { Get-Content -LiteralPath $ConsoleLog -Raw } else { '' }
    return @{ ExitCode = $proc.ExitCode; Text = $text }
}

Write-Host 'Step 1/2: Building PES3-Disc application...'
& (Join-Path $root 'Build-App.ps1')
if ($LASTEXITCODE -ne 0) { throw 'Build-App.ps1 failed.' }

$distDir = Join-Path $root 'dist'
if (-not (Test-Path -LiteralPath (Join-Path $distDir 'PES3-Disc.exe'))) {
    throw 'dist\PES3-Disc.exe not found after build.'
}

Write-Host ''
Write-Host 'Step 2/2: Compiling installer...'

$iscc = Get-InnoSetupCompiler
if (-not $iscc) {
    if ($env:GITHUB_ACTIONS -eq 'true' -or $env:CI -eq 'true') {
        throw 'Inno Setup 6 not found on build agent.'
    }
    Write-Host ''
    Write-Host 'Inno Setup 6 not found.' -ForegroundColor Yellow
    Write-Host 'Install from: https://jrsoftware.org/isdl.php' -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'Or run the PowerShell installer (Admin):' -ForegroundColor Cyan
    Write-Host "  powershell -ExecutionPolicy Bypass -File installer\Install-PES3-Disc.ps1"
    Write-Host ''
    Write-Host 'App binaries are ready in dist\'
    exit 0
}

$appVersion = '1.0.0'
if ($env:PES3_VERSION -match '^(\d+\.\d+\.\d+)$') {
    $appVersion = $Matches[1]
}

Write-Host 'Staging installer payload...'
if (Test-Path -LiteralPath $stageDir) {
    Remove-Item -LiteralPath $stageDir -Recurse -Force
}
New-Item -ItemType Directory -Path $stageDir -Force | Out-Null
Get-ChildItem -Path $distDir -Force | Copy-Item -Destination $stageDir -Recurse -Force
foreach ($helper in @('Install-DotNet-Runtimes.ps1', 'Install-DotNet-Runtimes.cmd')) {
    Copy-Item -LiteralPath (Join-Path $installerDir $helper) -Destination $stageDir -Force
}

if (-not (Test-Path -LiteralPath (Join-Path $stageDir 'PES3-Disc.exe'))) {
    throw 'installer\stage\PES3-Disc.exe missing after staging.'
}
$fileCount = (Get-ChildItem -LiteralPath $stageDir -Recurse -File).Count
Write-Host "Staged $fileCount file(s) in installer\stage\"

$generatedIss = Join-Path $installerDir 'generated-files.iss'
Write-InnoFilesInclude -StageDir $stageDir -OutPath $generatedIss
Write-Host "Wrote $generatedIss"

if (Test-Path -LiteralPath $outDir) {
    Remove-Item -LiteralPath $outDir -Recurse -Force -ErrorAction SilentlyContinue
}
New-Item -ItemType Directory -Path $outDir -Force | Out-Null

$logPath = Join-Path $outDir 'iscc.log'
$consoleLog = Join-Path $outDir 'iscc-console.txt'
$issName = Split-Path -Leaf $iss
$isccArgs = "/DMyAppVersion=$appVersion /Qp /Log=`"$logPath`" `"$issName`""

Write-Host "ISCC: $iscc"
Write-Host "Args: $isccArgs"

$exitCode = 1
$consoleText = ''
Push-Location $installerDir
try {
    for ($attempt = 1; $attempt -le 3; $attempt++) {
        $result = Invoke-Iscc -Compiler $iscc -WorkingDir $installerDir -Arguments $isccArgs -ConsoleLog $consoleLog
        $exitCode = $result.ExitCode
        $consoleText = $result.Text
        if ($consoleText) { Write-Host $consoleText }
        if ($exitCode -eq 0) { break }
        if ($attempt -lt 3) {
            Write-Host "Inno compile failed (exit $exitCode), retry $attempt/3..." -ForegroundColor Yellow
            Start-Sleep -Seconds 3
        }
    }
}
finally {
    Pop-Location
}

if ($exitCode -ne 0) {
    $logText = if (Test-Path -LiteralPath $logPath) { Get-Content -LiteralPath $logPath -Raw } else { '' }
    $genPreview = if (Test-Path -LiteralPath $generatedIss) {
        (Get-Content -LiteralPath $generatedIss -TotalCount 8) -join "`n"
    } else { '(missing)' }

    Write-Host '--- ISCC console ---' -ForegroundColor Red
    if ($consoleText) { Write-Host $consoleText } else { Write-Host '(empty)' }
    Write-Host '--- ISCC log file ---' -ForegroundColor Red
    if ($logText) { Write-Host $logText } else { Write-Host '(empty)' }
    Write-Host '--- generated-files.iss (first lines) ---' -ForegroundColor Red
    Write-Host $genPreview

    if ($env:GITHUB_ACTIONS -eq 'true') {
        $summary = @"
### ISCC console
$($consoleText.Trim())

### ISCC log
$($logText.Trim())

### generated-files.iss (preview)
$genPreview
"@
        "## Inno Setup failed (exit $exitCode)`n`n$summary" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
    }
    throw "Inno Setup compile failed (exit $exitCode)."
}

$setup = Get-ChildItem -LiteralPath $outDir -Filter 'PES3-Disc-Setup*.exe' | Select-Object -First 1
if (-not $setup) {
    throw "No PES3-Disc-Setup*.exe in $outDir"
}

Write-Host ''
Write-Host "Installer created: $($setup.FullName)"
Write-Host ''
Write-Host 'Give users this file. It will:'
Write-Host '  - Download and install .NET 8 Desktop Runtime'
Write-Host '  - Download and install .NET 10 Desktop Runtime'
Write-Host '  - Install PES3-Disc to Program Files'
Write-Host '  - Add Start menu shortcut'

exit 0
